### ISSUE TITLE
React TypeScript Template

### ISSUE THREAD

**Issue by ptaberg** [create-go-app/cli#1]
Hello,

I'd like to propose good React TypeScript template for your CLI. Let's make it a part of your org. I ready to make transfer. If you have issues of the template, let's discuss it. @koddr

**Comment by ptaberg** [comment]
This one https://github.com/ptaberg/react-ts-template

**Comment by koddr** [comment]
@ptaberg Hi!

Sorry, for delay, hard work these month...

Okay, LGTM to add it to CGAPP organization. If you want, I add you to organization.

**Comment by ptaberg** [comment]
@koddr, Yes, I want! Let's do great things!

**Comment by koddr** [comment]
@ptaberg done! Welcome 👍 

Check, if you can transfer or re-create repository from org, please.

**Comment by koddr** [comment]
Added to CLI. Thanks, again 😉
