### ISSUE TITLE
Adding robust web frameworks

### ISSUE THREAD

**Issue by imthaghost** [create-go-app/cli#100]
**Required check list:**

- [x] I'm gonna mark the checkboxes like this.
- [x] I didn't find in the Create Go App CLI repository's issues section similar feature request.
- [x] I understand, that the Create Go App CLI is Open Source and not-for-profit product.
- [x] This is not about third-party project, framework, package or technology.

**Is your feature request related to a problem? Please describe.**

Currently the cli only supports [net/http](https://github.com/create-go-app/net_http-go-template) and [fiber](https://github.com/create-go-app/fiber-go-template). [net/http](https://github.com/create-go-app/net_http-go-template) is great for a lightweight and clean backend but a bit slower to build with. Fiber is a nice framework designed to ease things up for fast development, however does not have a lot of feature support as it is built on top of [fasthttp](https://github.com/valyala/fasthttp). One of the main issues is that fiver [does not support HTTP/2](https://github.com/gofiber/fiber/issues/262).

**Describe the solution you'd like:**

I propose adding a robust framework that is compatible with the stdlib. Fiber is blazing fast, but faster than necessary at cost of not properly implementing a protocol and incompatibilities is not really the best. So I suggest adding other frameworks such as: [Echo](https://github.com/labstack/echo) , [Gin](https://github.com/gin-gonic/gin) , [Chi](https://github.com/go-chi/chi).

**Describe alternatives you've considered:**

I guess the alternative here is just building it from scratch? Not really any alternative solutions just would be nice to have other frameworks available.

**Comment by koddr** [comment]
Hi,

@imthaghost you absolutely rightly cited all the pros and cons of `Fiber` and `net/http`. 

> Even though I'm one of the fathers of Fiber (_and continue to be an important part of the process within the maintainer team_), I too feel that these preliminary templates for the backend will not be enough for the rapidly growing Go community around this project.

Unfortunately, I've only dealt with these two frameworks/toolkits in commercial production (under high load). For this reason, I can only rely on my experience in creating templates using them at the moment.

Yes, I tried to make pet projects in go-chi and Echo and Gin and even Iris (_although I know that in some layers of our community the author of this framework is often criticized for his behavior_). But I can't say with 100% certainty that I've studied them well enough to make another template for `Create Go App`.

> So, in every CLI release description, I ask the community for help in writing tests and creating backend templates with other frameworks... 🤷

But, I'm fully open to working together on a new template. And also, to the subsequent transfer of the repository to this project. Of course, with the inclusion of the author in the list of maintainers of the template and the `Create Go App` organization as a whole.

Thanks for this issue!

**Comment by imthaghost** [comment]
Hey,

@koddr thanks for the great reply!

> But, I'm fully open to working together on a new template. And also, to the subsequent transfer of the repository to this project. Of course, with the inclusion of the author in the list of maintainers of the template and the Create Go App organization as a whole.

I will try to get parity with the [fiber-template](https://github.com/create-go-app/fiber-go-template). You can see my progress [here](https://github.com/imthaghost/echo-template). Once I think it's in a solid place I will open a 
PR to merge into https://github.com/create-go-app/echo-go-template.

**Comment by koddr** [comment]
Hi,

Wow! It's wonderful news! Thanks 😉
