### ISSUE TITLE
Frontend folder was not generated

### ISSUE THREAD

**Issue by dhinojosac** [create-go-app/cli#114]
**Required check list:**

- [x] I'm gonna mark the checkboxes like this.
- [x] I didn't find in the Create Go App CLI repository's issues section similar bug.
- [x] I understand, that the Create Go App CLI is Open Source and not-for-profit product.
- [x] This is not about third-party project, framework, package or technology.

**My environment:**

- OS (`uname -a`): Windows 10
- Golang (`go version`): go 1.17 windows/amd64
- Create Go App CLI (`cgapp -v`): 3.3.1

**Describe the bug:**

I created some projects using cgapp, but none of them create the frontend folder.  I tried to create vue and react frontend to clear if was the type of front.

**Steps to reproduce the behavior:**

1. Go to project folder
2. cgapp create
3. choose backend framework (fiber)
4. choose frontend framework (vue/react)
5. choose web/proxy (nginx)
6. Confirm with Yes

**Expected behavior:**

I was expecting to see all the folders, but the frontend folder is lacking.

**Screenshots:**
![image](https://user-images.githubusercontent.com/5265771/148158877-ce57650f-1e2a-406b-8db5-5aee247102a4.png)

![image](https://user-images.githubusercontent.com/5265771/148159053-f8a1d579-a524-4e6d-9331-69640e5e344d.png)

**Additional context:**

**Comment by koddr** [comment]
Hi,

It's a part of Create Go App readme/wiki:

> Please make sure that you have npm version 7 or higher installed to create the frontend part of the project correctly.
>
> If you run the `cgapp create` command using our Docker image, npm of the correct version is already included.

Re-check this, please 😉

**Comment by dhinojosac** [comment]
Yes, I read it, thanks. Also, I installed ` create-vite@latest`.

**Comment by koddr** [comment]
Strangely, I just checked on macOS and the frontend folder with the selected framework has successfully created:

<img width="1103" alt="Screenshot 2022-01-05 at 08 36 46" src="https://user-images.githubusercontent.com/11155743/148165996-992cbffd-d406-424b-a66e-6354f20c5007.png">

Are all the correct permissions on the folder for the user who is doing the `cgapp create`? 
Unfortunately, I can't check on Windows machine.
