### ISSUE TITLE
Official website seems insecured

### ISSUE THREAD

**Issue by craph** [create-go-app/cli#121]
Hello,

I open this issue because I can't access your official website. It seems insecured.

![image](https://user-images.githubusercontent.com/14820052/154086975-21f725de-3041-4cc8-8cbb-aa4502cdaf49.png)

**Comment by koddr** [comment]
Hi,

Thanks for reaction, but this web address was a just 301 redirect to the project's [Wiki page](https://github.com/create-go-app/cli/wiki) on GitHub. You may use this instead :+1: 

> I'm planning to totally switch to GitHub built-in features for Create Go App CLI, without any redirects.
