### ISSUE TITLE
It creates the project even if I type n and press enter

### ISSUE THREAD

**Issue by VanoDevium** [create-go-app/cli#124]
**Required check list:**

- [x] I'm gonna mark the checkboxes like this.
- [x] I didn't find in the Create Go App CLI repository's issues section similar bug.
- [x] I understand, that the Create Go App CLI is Open Source and not-for-profit product.
- [x] This is not about third-party project, framework, package or technology.

**My environment:**

- OS (`uname -a`): `Linux 5.4.0-109-generic #123~18.04.1-Ubuntu SMP Fri Apr 8 09:48:52 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`
- Golang (`go version`): `go version go1.18.1 linux/amd64`
- Create Go App CLI (`cgapp -v`): `cgapp version 3.6.1`

**Describe the bug:**

**Steps to reproduce the behavior:**

1. cgapp create
2. select fiber
3. select none
4. select none
5. it asks Yes/No, I type `n`

**Expected behavior:**
I expect it stop creation, but it creates files: 
```
backend
hosts.ini
Makefile
playbook.yml
roles
```

**Comment by koddr** [comment]
Hi,

It's not really a _bug_. The point here is that the project sasts are created independently of each other. 

I think that we need to add additional checks at each step so that if an error occurs, delete **all parts** of the project that have already been created. 

If you have time to send such a **PR**, I will be very glad 😊

**Comment by VanoDevium** [comment]
@koddr 

I wanted to use cgapp to learn golang programming :))

But I have no choice :) I'll try to figure out how to fix it

**Comment by VanoDevium** [comment]
@koddr 
Looks like it was a bug after all..
There was no failure check (for NO answer) in the code at all :) 

I have added it. Please check.

**Comment by koddr** [comment]
Added in `v3.6.2` by merge your PR #126. 

Thanks! :+1:
