### ISSUE TITLE
cgapp create -> killed

### ISSUE THREAD

**Issue by gunnrcrakr** [create-go-app/cli#125]
When I try to create new app, I encountered some error. Please check below link

https://app.warp.dev/block/ko2R7dsCk8mwiMlz9lk3Uz

**Comment by gunnrcrakr** [comment]
After `brew uninstall cgapp` problem solved.

**Comment by koddr** [comment]
This can have nothing to do with `cgapp` itself. Please check the other packages that are installed on your system.

Maybe you have some _firewall_ configured with a strict degree of protection against application requests to the outside world 🤔

**Comment by lechnerio** [comment]
@koddr I have the same issue. I'm on a naked macbook pro and haven't installed anything besides a few basic (vscode, brew, react/vue).

**Comment by pmakowski23** [comment]
Same here, I just did the two commands that were in readme to install and when I try `cgapp create` it crashes with the same `[1]    48582 killed     cgapp create`

**Comment by vladdoster** [comment]
Thanks for creating this useful project!

---

I Hate to beat a dead horse, but for brevity...

I tested the x86_64 Darwin binary releases from v6.6.x - v6.4.x which all segfaulted.

However, installing via `go version go1.19.2 darwin/amd64` worked:

```bash
go install github.com/create-go-app/cli/v3/cmd/cgapp@latest
```
