### ISSUE TITLE
Add Database Mysql

### ISSUE THREAD

**Issue by jniltinho** [create-go-app/cli#127]
Add Database Mysql

- [x] I'm gonna mark the checkboxes like this.
- [ ] I didn't find in the Create Go App CLI repository's issues section similar feature request.
- [ ] I understand, that the Create Go App CLI is Open Source and not-for-profit product.
- [ ] This is not about third-party project, framework, package or technology.

![image](https://user-images.githubusercontent.com/1027494/169526140-9770b086-2887-48bb-bb71-4eeaf8bcfb1c.png)

**Comment by jniltinho** [comment]
> Hi,
> 
> Can you please send the PR with it?

https://github.com/create-go-app/fiber-go-template/pull/129

**Comment by koddr** [comment]
@jniltinho your PR was added to [create-go-app/fiber-go-template](https://github.com/create-go-app/fiber-go-template/releases/tag/v1.14.0) `v1.14.0` and ready to use.

Thank you :+1:
