### ISSUE TITLE
No `Frontend` folder gets created when `react-ts` is selected as frontend framework/library

### ISSUE THREAD

**Issue by pacholoamit** [create-go-app/cli#129]
**Required check list:**

- [x] I'm gonna mark the checkboxes like this.
- [x] I didn't find in the Create Go App CLI repository's issues section similar bug.
- [x] I understand, that the Create Go App CLI is Open Source and not-for-profit product.
- [x] This is not about third-party project, framework, package or technology.

**My environment:**

- OS : Linux windows 5.10.16.3-microsoft-standard-WSL2 #1 SMP Fri Apr 2 22:23:49 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
- Golang (`go version`): go version go1.18.3 linux/amd64
- Create Go App CLI (`cgapp -v`): cgapp version 3.6.2

**Describe the bug:**

If you follow the steps below, there is no `frontend` folder that gets generated for the `react-ts` framework/library

**Steps to reproduce the behavior:**

1. `mkdir GO-PROJECT`
2. `cd GO-PROJECT`
3. `cgapp create`
4. Select `fiber` as backend framework
5. Select `react-ts` as frontend framework/library
6. Select `traefik-acme-dns` as web/proxy server
7. Click `enter` to create project
8. No `frontend` folder is created

**Expected behavior:**

The project bootstraps properly including the `frontend` directory

**Screenshots:**

Image when running the commands
![image](https://user-images.githubusercontent.com/69985528/175576269-a2919f59-af50-43cc-ab0c-3b116f0764af.png)

Image of directory structure after commands, notice `frontend` is missing:
![image](https://user-images.githubusercontent.com/69985528/175576373-09001322-8e13-4abf-81cc-d665f3c199b3.png)

**Comment by koddr** [comment]
Hi,

Please make sure that you have npm version 7 or higher installed to create the frontend part of the project correctly. If you run the cgapp create command using our Docker image, npm of the correct version is already included.

**Comment by pacholoamit** [comment]
Ohhh right!! Awesome! It works now

**Comment by tolgadur** [comment]
I have npm version 8 and am seeing the same issue with a not so helpful error message:
```
Error: [ERROR]exit status 1
Usage:
  cgapp create [flags]
```

**Comment by nickali2** [comment]
using npm 9.6.4 I have the same issue. front-end folder didn't create (next-ts).

**Comment by nickali2** [comment]
using npm 9.6.4 I have the same issue. front-end folder didn't create (next-ts).

> **Required check list:**
> 
> * [x]  I'm gonna mark the checkboxes like this.
> * [x]  I didn't find in the Create Go App CLI repository's issues section similar bug.
> * [x]  I understand, that the Create Go App CLI is Open Source and not-for-profit product.
> * [x]  This is not about third-party project, framework, package or technology.
> 
> **My environment:**
> 
> * OS : Linux windows 5.10.16.3-microsoft-standard-WSL2 [React TypeScript Template #1](https://github.com/create-go-app/cli/issues/1) SMP Fri Apr 2 22:23:49 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
> * Golang (`go version`): go version go1.18.3 linux/amd64
> * Create Go App CLI (`cgapp -v`): cgapp version 3.6.2
> 
> **Describe the bug:**
> 
> If you follow the steps below, there is no `frontend` folder that gets generated for the `react-ts` framework/library
> 
> **Steps to reproduce the behavior:**
> 
> 1. `mkdir GO-PROJECT`
> 2. `cd GO-PROJECT`
> 3. `cgapp create`
> 4. Select `fiber` as backend framework
> 5. Select `react-ts` as frontend framework/library
> 6. Select `traefik-acme-dns` as web/proxy server
> 7. Click `enter` to create project
> 8. No `frontend` folder is created
> 
> **Expected behavior:**
> 
> The project bootstraps properly including the `frontend` directory
> 
> **Screenshots:**
> 
> Image when running the commands ![image](https://user-images.githubusercontent.com/69985528/175576269-a2919f59-af50-43cc-ab0c-3b116f0764af.png)
> 
> Image of directory structure after commands, notice `frontend` is missing: ![image](https://user-images.githubusercontent.com/69985528/175576373-09001322-8e13-4abf-81cc-d665f3c199b3.png)

using npm 9.6.4 I have the same issue. front-end folder didn't create (next-ts).

**Comment by koddr** [comment]
Hi,

Can you try a similar installation `next-ts` via create-next-app on your machine?
