### ISSUE TITLE
[BUG] Unable to create new app on latest version when using a custom template.

### ISSUE THREAD

**Issue by mystique09** [create-go-app/cli#132]
**Required check list:**

- [x] I'm gonna mark the checkboxes like this.
- [x] I didn't find in the Create Go App CLI repository's issues section similar bug.
- [x] I understand, that the Create Go App CLI is Open Source and not-for-profit product.
- [x] This is not about third-party project, framework, package or technology.

**My environment:**

- Linux Ubuntu SMP x86_64 GNU/Linux
- go version go1.19.2 linux/amd64
- cgapp version 3.6.2

**Describe the bug:**

Bug when creating a new app with custom template, In last prompt ```Y``` choice is still a No.

**Steps to reproduce the behavior:**

1. run ```cgapp create -t```
2. In my case, I choose echo-go-template as backend template, so input ```github.com/create-go-app/echo-go-template```
3. Do the same thing for the frontend(pick your own frontend template).
4. Lastly, type ```Y``` for the last prompt.

**Expected behavior:**

The app picks the ```no``` choice and closes.

**Screenshots:**

![bug](https://user-images.githubusercontent.com/50514928/201716835-80262bb5-0c6a-4fea-b489-0dd74bc75bd9.png)

**Comment by koddr** [comment]
Hi,

@mystique09 if you've time, would be great to make PR with this fix 😉
