### ISSUE TITLE
cannot create app in M1 mac

### ISSUE THREAD

**Issue by joonseolee** [create-go-app/cli#139]
**Required check list:**

- [x] I'm gonna mark the checkboxes like this.
- [ ] I didn't find in the Create Go App CLI repository's issues section similar bug.
- [X] I understand, that the Create Go App CLI is Open Source and not-for-profit product.
- [X] This is not about third-party project, framework, package or technology.

**My environment:**

- OS (`uname -a`): `Darwin USERMN001 21.6.0 Darwin Kernel Version 21.6.0: Sun Nov  6 23:31:13 PST 2022; root:xnu-8020.240.14~1/RELEASE_ARM64_T6000 arm64`
- Golang (`go version`): `go version go1.19.5 darwin/arm64`
- Create Go App CLI (`cgapp -v`): `[1]    53755 killed     cgapp -v`

**Describe the bug:**

**Steps to reproduce the behavior:**

I typed the `cgapp create` command, then came out an error the below screenshot.  
I have looked for some similar issues like this in the websites. 
However I couldn't find the error for m1 mac.  

**Expected behavior:**

I would like to genereate a project properly.  

**Screenshots:**

<img width="457" alt="image" src="https://user-images.githubusercontent.com/43516757/215620847-9b84106c-3c8c-44ae-a6df-2e4caa77c23d.png">

**Additional context:**

**Comment by koddr** [comment]
Hi,

Can you please try to install this CLI via `go install` or brew package manager?

**Comment by joonseolee** [comment]
@koddr 
Hi, thank you for your response.  
btw, I don't know why it works because, I already faced the fact that it didn't work to do with brew.  
I thought somebody needed to work out this issue, but the issue was me 😅
Anyway, thank you !
