### ISSUE TITLE
Does not work on Apple M1 computer

### ISSUE THREAD

**Issue by binyamindavid** [create-go-app/cli#142]
**Required check list:**

- [x] I'm gonna mark the checkboxes like this.
- [x] I didn't find in the Create Go App CLI repository's issues section similar bug.
- [x] I understand, that the Create Go App CLI is Open Source and not-for-profit product.
- [x] This is not about third-party project, framework, package or technology.

**My environment:**

- OS `Ventura 13.2.1 (22D68)`:
- Golang (`go version go1.20.2 darwin/arm64`):
- Create Go App CLI (`cgapp -v`):

**Describe the bug:**

**Steps to reproduce the behavior:**

1. Go to Terminal
2. Click on type cgapp create
3.  I get `[1]    9955 killed     cgapp create`

**Expected behavior:**

I expect to see the process for creating the app. 

**Screenshots:**
![Screenshot 2023-03-14 at 9 50 31](https://user-images.githubusercontent.com/972227/224931559-1d66c79e-d1ae-4271-8471-876f91e9bf72.png)

**Additional context:**

**Comment by moza88** [comment]
Could you try running it with Docker? `docker run --rm -it -v ${PWD}:${PWD} -w ${PWD} koddr/cgapp:latest [COMMAND]`
