### ISSUE TITLE
Deploy failled

### ISSUE THREAD

**Issue by minhphamba-ct** [create-go-app/cli#152]
**Required check list:**

- [ ] I didn't find in the repository's issues section a similar bug.
- [x] I understand, this is an Open Source and not-for-profit product.
- [ ] This is not about a third-party project, framework, or technology.

**My environment:**

- OS (`mac os`):
- Go (`1.20`):

**Describe the bug:**
_A clear and concise description of what the bug is._

- When I executed `cgapp deploy`. I got an error message: `Error: [ERROR][ERROR]exec: "ansible-playbook": executable file not found in $PATH`

**Steps to reproduce the behavior:**

1. Create Go App with `cgapp create`
2. Deploy: `cgapp deploy`

**Screenshots:**
_If applicable, add screenshots to help explain your problem._
![Screenshot 2023-08-01 at 23 45 16](https://github.com/create-go-app/cli/assets/113890133/17a94964-f5f8-4919-bd2d-7c70dde7c10e)

**Comment by koddr** [comment]
Hi,

Did you install Ansible on your PC? 🤔

**Comment by minhphamba-ct** [comment]
Thank you, After I installed Ansible, it worked

**Comment by minhphamba-ct** [comment]
I hope you will make 1 thread with mongodb in the future @koddr
