### ISSUE TITLE
front-end folder was not created

### ISSUE THREAD

**Issue by nickali2** [create-go-app/cli#154]
**Required check list:**

- [✔️] I didn't find in the repository's issues section a similar bug.
- [✔️] I understand, this is an Open Source and not-for-profit product.
- [✔️] This is not about a third-party project, framework, or technology.

**My environment:**

- OS (`uname -a`): win 11
- Go (`go version`): 1.21.0
- npm 9.8.1
- go-cli 4.0.1

**Describe the bug:**
_I created a project but front-end folder didn't create.

**Steps to reproduce the behavior:**

1. run cgapp create
2. select fiber as backend framework
3. select next-ts as front-end
4. select traefik
5. select Yes to start create

**Expected behavior:**
_A clear and concise description of what you expected to happen._
i expected that front-end, backend , and other folders created but there was no front-end here

**Screenshots:**
![image](https://github.com/create-go-app/cli/assets/23019220/17067f5e-9908-4951-8435-e0c57e6fb444)
![image](https://github.com/create-go-app/cli/assets/23019220/ff361795-53d8-4eeb-8432-b42ba33d64e9)

**Comment by koddr** [comment]
Hi,

Did you install `npm` v7 or higher on your system?

**Comment by koddr** [comment]
Fixed in `v4.1.0`

**Comment by front123** [comment]
I have the same issue in cgapp v4.1.0.
