### ISSUE TITLE
Visiting the website "https://create-go.app" returns a Privacy Error  

### ISSUE THREAD

**Issue by RomanMunar** [create-go-app/cli#2]
**Bug Description**
Visiting the website, returns the following error:
```NET::ERR_CERT_COMMON_NAME_INVALID```
The Certificate issued in the website is invalid.

**To Reproduce**

1. Go to '[https://create-go.app](https://create-go.app)'
2. See error

**Screenshots**
![Screenshot_20200625_144848](https://user-images.githubusercontent.com/50381110/85670247-4b02bc00-b6f3-11ea-92be-11266ff75805.png)

**My environment:**
- OS :
Linux Ubuntu 18.04 x86_64
- Browser:
Brave Browser (chromium derivative)

**Additional context**
The error seems to be caused by an invalid certificate issued from let's encrypt

**Comment by koddr** [comment]
@RomanMunar hi! Thanks for report.

Yep, at this time, website is down, because under construction. If you have any ideas for content or visual elements/features you're welcome 👍  My plan is release website in the middle of July with simple docs (maybe, I'll use MkDocs engine for it).

**Comment by koddr** [comment]
@RomanMunar website is online now 😉 

Please, visit https://create-go.app
