### ISSUE TITLE
Failed without appropriate error on missing node lib.

### ISSUE THREAD

**Issue by SAThomsen** [create-go-app/cli#49]
**Required check list:**

- [x] I'm gonna mark the checkboxes like this.
- [x] I didn't find in the Create Go App CLI repository's issues section similar bug.
- [x] I understand, that the Create Go App CLI is Open Source and not-for-profit product.
- [x] This is not about third-party project, framework, package or technology.

**My environment:**

- OS (`uname -a`): Darwin Sebastians-MacBook-Pro.local 19.6.0 Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEASE_X86_64 x86_64
- Golang (`go version`): go version go1.15.6 darwin/amd64
- Create Go App CLI (`cgapp -v`): cgapp version 1.6.10

**Describe the bug:**

When running `cgapp create` the initiation of the frontend failed. It failed because I didn't have node installed. A better error message here would improve the UX.
**Steps to reproduce the behavior:**

1. Have system without `nodejs` installed.
2. Run `cgapp create`
3. Notice the sparse error message.

**Expected behavior:**

A clear error message describing the reason for the error. 

**Screenshot**
![image](https://user-images.githubusercontent.com/11570929/102773201-2711f180-4389-11eb-8ffb-9009bade2e46.png)

Cheers!
Thank you for your hard work.

**Comment by koddr** [comment]
Hi, @SAThomsen! Thanks for this UX request.

Yes, I'll make this error message _more_ user-friendly on next version.

**Comment by SAThomsen** [comment]
Sounds create thanks :)!

**Comment by koddr** [comment]
@SAThomsen thx for issue :D 

But I really have no idea, what's wrong.. can you please record some video or logs or ... for this process?
