### ISSUE TITLE
Golang jwt dependency is no longer maintained

### ISSUE THREAD

**Issue by Lavariet** [create-go-app/cli#91]
According to dgrijalva his repository https://github.com/dgrijalva/jwt-go is no longer maintained and has been archived.

Based on the following discussion https://github.com/dgrijalva/jwt-go/issues/462 a new repo has been created.

Would it be possible to switch the dependency to https://github.com/golang-jwt/jwt?

**Comment by koddr** [comment]
@Lavariet thanks for this issue! Update is coming.

**Comment by koddr** [comment]
All project's updates are done! ✅
