### ISSUE TITLE
Backend module name from user's input.

### ISSUE THREAD

**Issue by byouloh** [create-go-app/cli#95]
**Required check list:**

- [x] I'm gonna mark the checkboxes like this.
- [ ] I didn't find in the Create Go App CLI repository's issues section similar feature request.
- [ ] I understand, that the Create Go App CLI is Open Source and not-for-profit product.
- [ ] This is not about third-party project, framework, package or technology.

**Is your feature request related to a problem? Please describe.**

No! But for beginner your backend module name is a little bit confusing.

**Describe the solution you'd like:**

Your CLI tool has 4 inputs from user.
How about adding another input for the backend module name from user.
And then the user can see his module name in the go.mod file.

**Describe alternatives you've considered:**

**Screenshots:**

**Additional context:**

**Comment by koddr** [comment]
@byouloh hi!

Please follow the established rules when creating an issue (_for example, you did not set all the checkboxes and did not specify anything in the "Describe alternatives you've considered" section_). Filling out a complete template helps us tremendously in understanding your problem or question. 🙏

> How about adding another input for the backend module name from user.

Thanks for investigating.

Especially for beginners, the phrase like "_give your backend's name for the `go.mod` file_" will be more confusing than the presence of the default backend package name. This is my opinion. 🤔

Likewise, nothing prevents the user from renaming his backend in `go.mod` as he likes! Yes, it will cause some inconvenience in renaming some project files... but adding the backend code generation in the CLI would be too costly and unnecessary operation (_at this time of project development_).

If you want to help to improve the project, [Create Go App](https://github.com/create-go-app) is completely Open Source, make a PR with edits, we will check it and release a new version with this feature! 😉

**Comment by byouloh** [comment]
@koddr hi,

Thank you for your opinion.
I like to use your tool nowadays, especially good for deployment.
I think I can close this issue.
