### ISSUE TITLE
Error: [ERROR] [ERROR] When creating new app

### ISSUE THREAD

**Issue by goliatone** [create-go-app/cli#97]
**Required check list:**

- [x] I'm gonna mark the checkboxes like this.
- [x] I didn't find in the Create Go App CLI repository's issues section similar bug.
- [x] I understand, that the Create Go App CLI is Open Source and not-for-profit product.
- [x] This is not about third-party project, framework, package or technology.

**My environment:**

- OS (`uname -a`): **Darwin not.your.bussiness.net 19.6.0 Darwin Kernel Version 19.6.0: Thu Oct 29 22:56:45 PDT 2020; root:xnu-6153.141.2.2~1/RELEASE_X86_64 x86_64**
- Golang (`go version`): **go version go1.17.1 darwin/amd64**
- Create Go App CLI (`cgapp -v`): **cgapp version 3.0.0**

**Describe the bug:**

It will create the **backend** directory but no **frontend**. Tried with different options for the front end choices with the same result/output. 

**Steps to reproduce the behavior:**

Create a new project

```
% cgapp create                                                                            /tmp/test-go


Create a new project via Create Go App CLI v3.0.0...

[?] Choose a backend framework: fiber
[?] Choose a frontend framework/library: svelte-ts
[?] Choose a web/proxy server: traefik
[?] If everything is okay, can I create this project for you? ;) Yes

[OK] Backend was created with template `github.com/create-go-app/fiber-go-template`!
Error: [ERROR] [ERROR] 
Usage:
  cgapp create [flags]

Aliases:
  create, new

Flags:
  -h, --help       help for create
  -t, --template   enables to use custom backend and frontend templates

```

**Expected behavior:**

Have a fully working application

**Comment by koddr** [comment]
Hi,

It looks like you don't have Node.js installed with `npm` version `7` or higher. 
Please take a look at this and try again to create a new project.

Furthermore, you can use Docker-way to create.

**Comment by goliatone** [comment]
@koddr I actually do have node installed `v16.5.0`. I am using `nvm` if that matters at all?

**Comment by koddr** [comment]
@goliatone absolutely!

That's accurately what it says in the project [Wiki](https://github.com/create-go-app/cli/wiki/Errors-in-the-process#in-creating-the-project) and [README](https://github.com/create-go-app/cli#frontend): 

> Please make sure that you have `npm` version `7` or higher installed to create the frontend part of the project correctly. If you run the `cgapp create` command using our [Docker image](https://github.com/create-go-app/cli#-docker-way-to-quick-start), `npm` of the correct version is **already** included.
