### ISSUE TITLE
Vite create err

### ISSUE THREAD

**Issue by hotrungnhan** [create-go-app/cli#98]
**Required check list:**

- [x] I'm gonna mark the checkboxes like this.
- [x] I didn't find in the Create Go App CLI repository's issues section similar bug.
- [x] I understand, that the Create Go App CLI is Open Source and not-for-profit product.
- [x] This is not about third-party project, framework, package or technology.

**My environment:**

- OS (`uname -a`): Window 11
- Golang (`go version`): go1.16.7
- Create Go App CLI (`cgapp -v`): 3.0.0

**Describe the bug:**
```

Create a new project via Create Go App CLI v3.0.0...

[?] Choose a backend framework: fiber
[?] Choose a frontend framework/library: vue-ts
[?] Choose a web/proxy server: nginx
[?] If everything is okay, can I create this project for you? ;) Yes

[OK] Backend was created with template `github.com/create-go-app/fiber-go-template`!
Error: [ERROR] [ERROR] Error: EPERM: operation not permitted, mkdir 'C:\Users\Kudou'
command not found: create-vite

Usage:
  cgapp create [flags]

Aliases:
  create, new

Flags:
  -h, --help       help for create
  -t, --template   enables to use custom backend and frontend templates
```

I was install vite , vue ,... as the global of npm. But when select vue-ts , it say command not found "create-vite"
**Steps to reproduce the behavior:**

1. Go to ...
2. Click on ...
3. ...

**Expected behavior:**

**Screenshots:**

**Additional context:**

**Comment by koddr** [comment]
Hi,

As indicated in the error (`Error: EPERM: operation not permitted, mkdir 'C:\Users\Kudou'`), try giving access to the folder in which you want to create a new project.

Moreover, you can always use a ready-made [Docker image](https://github.com/create-go-app/cli#-docker-way-to-quick-start) that already has everything you need to create a project.

**Comment by hotrungnhan** [comment]
i dont know how but i try update npm as global , it seem to work.
``` js
npm install -g npm@latest --force 
```

**Comment by koddr** [comment]
@hotrungnhan yes, it's correct!

That's accurately what it says in the project [Wiki](https://github.com/create-go-app/cli/wiki/Errors-in-the-process#in-creating-the-project) and [README](https://github.com/create-go-app/cli#frontend): 

> Please make sure that you have `npm` version `7` or higher installed to create the frontend part of the project correctly. If you run the `cgapp create` command using our [Docker image](https://github.com/create-go-app/cli#-docker-way-to-quick-start), `npm` of the correct version is **already** included.
